### ISSUE TITLE
How to send bigger payloads?

### ISSUE THREAD

**Issue by ITler** [slack-go/slack#1197]
### Disclaimer
Probably not the right place to ask, but I don't know a better one

### What happened
I have a simple client implementation which supposes to send a bigger payload using `PostMessage`  function from `chat.go`

My message structure looks like: **[this](https://app.slack.com/block-kit-builder/T07DBAMS9#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22:rotating_light:%20Found%20overdue%20Pull%20Requests%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*%3Cgithub.com%7Crepo1%3E*:%22%7D%7D,%7B%22type%22:%22context%22,%22elements%22:%5B%7B%22type%22:%22image%22,%22image_url%22:%22https://emoji.slack-edge.com/T7RBBBXHB/github-pr/10f0cf332f6a8e93.png%22,%22alt_text%22:%22Github%20PR%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*%3Cgithub.com%7Cfeat:%20do%20stuff%3E*%5Cn(id=#12345,%20created_at=2023-01-05Z11:12:13)%22%7D%5D%7D,%7B%22type%22:%22context%22,%22elements%22:%5B%7B%22type%22:%22image%22,%22image_url%22:%22https://emoji.slack-edge.com/T7RBBBXHB/github-pr/10f0cf332f6a8e93.png%22,%22alt_text%22:%22Location%20Pin%20Icon%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*%3Cgithub.com%7Cfeat:%20do%20smore%20tuff%3E*%5Cn(id=#23456,%20created_at=2023-01-06Z11:12:13)%22%7D%5D%7D,%7B%22type%22:%22divider%22%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*%3Cgithub.com%7Crepo2%3E*:%22%7D%7D,%7B%22type%22:%22context%22,%22elements%22:%5B%7B%22type%22:%22image%22,%22image_url%22:%22https://emoji.slack-edge.com/T7RBBBXHB/github-pr/10f0cf332f6a8e93.png%22,%22alt_text%22:%22Github%20PR%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*%3Cgithub.com%7Cfix:%20fancy%20fix%3E*%5Cn(id=#1345,%20created_at=2023-01-03Z11:12:13)%22%7D%5D%7D,%7B%22type%22:%22context%22,%22elements%22:%5B%7B%22type%22:%22image%22,%22image_url%22:%22https://emoji.slack-edge.com/T7RBBBXHB/github-pr/10f0cf332f6a8e93.png%22,%22alt_text%22:%22Location%20Pin%20Icon%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*%3Cgithub.com%7Cfix:%20some%20other%20PR%20title%3E*%5Cn(id=#5234,%20created_at=2023-01-07Z17:12:13)%22%7D%5D%7D%5D%7D)**

Of cause these are test data, but in reality, I would have quite a lot of real data (queried via Github API). When sending the bigger amount of data, I got `invalid_blocks` returned.
It seems, due to the amount of datasets I would want to process, the payload becomes too large.
If so, I would have wished for a more precise error message than `invalid_blocks`. 

### Expected behavior
However, more important: I would like to send my data. 
**How to overcome the limitation** I am facing here?

I could send multiple messages (each for one repo dataset that I want to send) , but it also wouldn't scale if the number of pull requests gets too high.

### Steps to reproduce
```go
api := slack.New("YOUR_TOKEN_HERE")
var blocks []slack.Block = blocksComposeMagic() // see block kit link above to see what would get composed here
channelID, timestamp, err := api.PostMessage(
	"CHANNEL_ID",
	slack.MsgOptionText("Some text", false),
	slack.MsgOptionBlocks(blocks),
	slack.MsgOptionAsUser(true),
)
if err != nil {
	fmt.Printf("%s\n", err)
	return
}
fmt.Printf("Message successfully sent to channel %s at %s", channelID, timestamp)
```

#### manifest.yaml
none

### Versions
- Go:  1.20.3
- slack-go/slack: 0.12.2

**Comment by mtintes** [comment]
Not a maintainer, but maybe I can help. [This](https://api.slack.com/reference/block-kit/blocks) is probably the limitation you are running into. You would hit the 50 blocks pretty quick. Are users pulling the data, like "Hey chatbot, give me all my PRs" and they get all their open PRs? or is this more of a push like a cron job executed and now you are publishing the results at once to Slack?

If it is the former you could ask them if they want everything or just a specific repo using a combo box, or at least if you are going to spam them (breaking up by repo probably makes sense) then they get it all because they chose that (maybe they get a DM with all the info at that point).

If it is just a bulk process you could also shove it into a file and publish a file instead. I would say that chat schemes that get too chatty are a bad pattern since people tend to start to ignore the info. It really all depends on what is pulling the data, who it's going to, how many people need to see it etc.

I had a thing a while ago where you could ask the bot for all the PRs for a team. One team had dozens of repos and it got big quick so they always got theirs as a spreadsheet or a text file(can't remember exactly). You got some options, not always pretty, but there are some.

**Comment by ITler** [comment]
Thank you Mike (@mtintes)

I just overlooked this 50 blocks limitation. My bad. Thanks for pointing it out.
> I had a thing a while ago where you could ask the bot for all the PRs for a team. One team had dozens of repos and it got big quick so they always got theirs as a spreadsheet or a text file(can't remember exactly). You got some options, not always pretty, but there are some.

Exactly our use-case, but not a chatbot implementation. It lists all PRs per a growing set of repos that have a certain age and we want to use it to inform 'a person in charge per day' to tackle findings.

Also thanks for sharing your view on 'bad pattern'.
 I tend to agree, while I think that assembling a file indeed might be the better approach here. I will chase that approach.
