### ISSUE TITLE
How about mentioning User method

### ISSUE THREAD

**Issue by sinramyeon** [slack-go/slack#177]
Using slacklistener.client.PostMessage or SendMessage is not bad for use attachments, but how about make specific method for mentioning or dm to specific user?

**Comment by sinramyeon** [comment]
I know it can be add text area like <@userId>, but It could be easier to make method like SendUserMention(channel, text string, id string, params PostMessageParameters) *id is User.ID(Maybe we can just do it for User.Name)... If it sounds like not shit, I'll get it on my own

**Comment by lrstanley** [comment]
IMO, I don't think this should be implemented, given it's a very trivial to prefix the message with such a field, as well as there is no common/standard way to do such things. Some users may not prefer the type of format of the message (e.g. some may just prefer `@user: <message>` or `[@user] <message>`, rather than `<@user> <message>`), and as such I don't think it should be the job of this package to impose such methods.

It's.. been more than a few months, so I'm sure you've already made your own wrappers for these types of things anyway.

**Comment by sinramyeon** [comment]
@lrstanley I did, and i completely agree with your opinion. Thanks for reply my question!
