### ISSUE TITLE
Token with scope to CreateChannel

### ISSUE THREAD

**Issue by bliitzkrieg** [slack-go/slack#197]
I am trying to create a bot that creates channels via a /command. Is this possible? I was looking at the documentation and both custom and app bots don't have that access to that scope. 

What are my options? Has anybody had any luck with this?

The permissions are here: https://api.slack.com/bot-users

**Comment by bliitzkrieg** [comment]
Looks like only user tokens can create channels. Is there anyway to get a user token without having to do an oauth flow?

https://api.slack.com/methods/channels.create

**Comment by lrstanley** [comment]
Not sure if you have figured it out already, but when you create a Slack App, you can give the app the `channels:write` permission under **OAuth & Permissions** >> **Select Permission Scopes**, which will let them create channels. Then you just need to use the apps token rather than the bots token for the channel creation requests.
