### ISSUE TITLE
Unable to complete connection

### ISSUE THREAD

**Issue by arcimboldo** [slack-go/slack#239]
First of all, I suspect this might be an issue with the configuration of the bot on slack website, because the same code works on a different slack account/workspace, but I cannot compare the configuration.

The issue is as follow: when I start the bot it looks like authentication is correct, but then the bot receive an empty event and starts flooding slack with `PING` until the connection is closed.

```
slack-bot: 2018/01/07 12:19:57 misc.go:79: parseResponseBody: {"ok":true,"self":{"id":"U8NG78932","name":"napp","prefs ...
slack-bot: 2018/01/07 12:19:57 slack.go:92: Using URL: wss://mpmulti-xxxx.lb.slack-msgs.com/websocket/...
Connection counter: 1
slack-bot: 2018/01/07 12:19:58 slack.go:92: Incoming Event: {}
slack-bot: 2018/01/07 12:19:58 slack.go:92: Sending PING  1
slack-bot: 2018/01/07 12:19:58 slack.go:92: Sending PING  2
slack-bot: 2018/01/07 12:19:58 slack.go:92: Sending PING  3
...
slack-bot: 2018/01/07 12:19:58 slack.go:92: Sending PING  1587slack-bot: 2018/01/07 12:19:59 slack.go:86: RTM Error sending 'PING 1749': write tcp 172.22.1.42:64433->35.187.106.147:443: write: broken pipe
slack-bot: 2018/01/07 12:19:59 slack.go:92: killing connection
slack-bot: 2018/01/07 12:19:59 misc.go:79: parseResponseBody: {"ok":true}
```

**Comment by luketc1** [comment]
I'm seeing the same behavior, my application is no longer able to connect either.

**Comment by robertBojor** [comment]
Same here... it ends up sending over a thousand pings and just fails after that with Too Many Requests...

```
...
nlopes/slack2018/01/09 09:36:16 slack.go:92: Incoming Event: {}
nlopes/slack2018/01/09 09:36:16 slack.go:92: Sending PING  14
nlopes/slack2018/01/09 09:36:16 slack.go:92: Sending PING  15
nlopes/slack2018/01/09 09:36:16 slack.go:92: Sending PING  16
nlopes/slack2018/01/09 09:36:16 slack.go:92: Sending PING  17
nlopes/slack2018/01/09 09:36:16 slack.go:86: RTM Error sending 'PING 17': write tcp 172.31.13.247:39334->35.165.91.153:443: write: broken pipe
nlopes/slack2018/01/09 09:36:16 slack.go:92: killing connection
nlopes/slack2018/01/09 09:36:16 misc.go:79: parseResponseBody: {"ok":true,"no_op":true,"already_open":true,"channel":{"id":"D5MQJHA1M"}}
nlopes/slack2018/01/09 09:36:16 misc.go:164: HTTP/2.0 429 Too Many Requests
...
```

**Comment by Davejkane** [comment]
Also experiencing this issue. I have a connection counter that as of around 16 hours ago started spinning out of control and now we're getting a 429: too many requests. I must say, we haven't updated this package in quite a while though.

**Comment by robertBojor** [comment]
Update: After updating the Go package `go get -u ...` the issue has gone away, so it's just because of an older package version.

**Comment by arcimboldo** [comment]
@robertBojor it didn't work for me: I'm vendoring `github.com/nlopes/slack` but after `govendor update +vendor` the problem still persists.

Besides: the same bot works on a different workspace (paid plan)

**Comment by thecrogers** [comment]
I was able to get slack bot back online by updating to latest commit on master.
https://github.com/nlopes/slack/commit/107290b5bbaf3e634833346bb4ff389b1c782bc7
  Note that the last release v0.1.0 will not work.

**Comment by zanderz** [comment]
We had this too, and revendoring didn't work at first, but after stopping our bot for 15 minutes or so it started working again.

**Comment by Jmainguy** [comment]
getting latest code fixed this for me as well.

**Comment by dagoonline** [comment]
Same here starting today. Probably an internal api change in slack being rolled out. Would be great to have a new release with latest code, it works fine (at least for this part).

**Comment by ArcticSnowman** [comment]
Our GO based bots got terminated and even with an update to the latest package, still getting rate-limited and I've tried deleting and adding a new bot integration into slack.

**Comment by ArcticSnowman** [comment]
Seems to be a fall out from last Wednesday's slack outage.

**Comment by ArcticSnowman** [comment]
```
Jan 12 11:54:41|intdas01-dev3| nlopes/slack2018/01/12 11:54:41 websocket_managed_conn.go:113: reconnection 14 failed: persistent connection closed
Jan 12 11:54:41|intdas01-dev3| nlopes/slack2018/01/12 11:54:41 websocket_managed_conn.go:114:  -> reconnecting in 4m39.001568924s
```

**Comment by thecrogers** [comment]
@GrantStreetGroup, Not sure what resource you are being rate limited on, but I would imagine that the outage on Wednesday was a deploy to an update api version. Which also probably removed some deprecated endpoints, and resources.

You might want to make sure that your bot/s are not trying to used some deprecated resource.  Since the last released version of this repo was well over 7 months ago.

**Comment by ArcticSnowman** [comment]
Hmm... maybe something in github.com/BeepBoopHQ/go-slackbot that's needs a fix.

**Comment by arcimboldo** [comment]
I can confirm that after the update of the code and after a few days it started working again. Since it looks like nobody has this issue anymore I think I am closing this ticket.

**Comment by aoberoi** [comment]
Hey folks, Slack Platform engineer here :wave:

We’ve noticed many bots using this library have had issues connecting to RTM over the last couple days. I want to bring some clarity around what happened.

We’re rolling out a change (to a percentage of teams at a time and it will reach 100% relatively soon) that slightly modifies the websocket URL you receive after calling `rtm.start` or `rtm.connect` web API methods. The difference is there is a query string included, where there was none before.

That seems to have tripped up the code in this package. But I’m really happy to see the smart folks that work on this package and the community of its users come together to find a fix! Since we’ve identified the cause we’re trying to do our part and proactively reach out to the larger bots on our platform that seemingly use this package to give them a heads-up about the change and point them to updating this package to minimize impact on their operations. 

Please feel free to reach me if you have any further questions about this change. I’m @aoberoi on twitter and the Bot Developer Hangout (http://dev4slack.xoxco.com/). Once we’re out of the woods on this issue, I’d love to chat with the maintainers to see if there’s anything we can do to work more smoothly with you in the future.

**Comment by aoberoi** [comment]
Oh, one more thing. After applying the latest update, you may need to remain disconnected for several minutes before trying to connect again. That’s because the `rtm.start` and `rtm.connect` methods are rare-limited, and since your bot was likely hammering those methods previously to try and reconnect, our platform would like you to slow down.

There’s definitely an opportunity for an enhancement to the code to deal with the 429 response code and retry headers in a more intelligent way. We should probably spin up another Issue for this feature.

**Comment by ArcticSnowman** [comment]
#240

**Comment by ArcticSnowman** [comment]
I updated my code and even recreated a new slack bot integration and it still fails...

**Comment by aoberoi** [comment]
@ArcticSnowman we can try to take a closer look if you email devsupport@slack.com

**Comment by ArcticSnowman** [comment]
@aoberoi Already have a ticket open with Slack...    

I tried out the changes in the PR #238 and the bot started working...
