### ISSUE TITLE
Slack connection issues

### ISSUE THREAD

**Issue by james-lawrence** [slack-go/slack#248]
@aoberoi @ArcticSnowman, 

lets move the conversation here.

basically, unless slack comes up with a way for us to reliable test the library against the API changes they've made there isn't much coordinating or time I'd want to spend on this issue.

From what I can tell most people resolved their issue with an update to the latest of this library, we can't be sure if thats due to changes here or changes slack made in response to increased error rates.

regarding @ArcticSnowman's issue: seems likely you may have a singular problem related to your environment particularly if you are running through a proxy. best suggestion I can offer is to connecting using a token from outside your normal deployed environment and see if that resolves the issue.

**Comment by aoberoi** [comment]
agreed about separating this issue from #238, just wanted to add the annotation since some of the data about the issue was in comments there.

i'll continue to look into the exact behavior of the `user-agent` parsing patch so we can reliably determine how to trigger the Slack-side codepath where the issue was first seen. no need to try this out until i can confirm it, but i think the necessary steps will be:
1) connecting to a team that has already been migrated (which @ArcticSnowman is, since you see `?dp=1` at the end of the websocket URL)
2) altering the User-Agent so that it is *not* `Go-http-client/2.0`

in the meantime, i agree that it would be wise to try eliminating the squid proxy as a cause for the issue. @ArcticSnowman, would it be possible to try connecting without the proxy, even temporarily? i wouldn't want you to circumvent any security policies, but maybe standing up another instance of this application that has no real data access would be an option.

**Comment by ArcticSnowman** [comment]
@aoberoi - might take me a day or two to set something up..  I'll craft a cut down bot that I can run outside..   that will just test we can connect..   

Is there a testing endpoint that I can use, which you can have higher tracing level on the Slack end?

**Comment by aoberoi** [comment]
@ArcticSnowman: nope, the URL is the one you get back from the `rtm.start` call, we wouldn’t be testing the same code path if I gave you something different.

I have an update regarding how Slack is handling the changes. Rather than using a querystring at all (`?dp=1`), we’ve opted to add a subdomain to the host. This proved to be very successful, and now 100% of teams are using the _new_ code path. No user-agent parsing at all!

Now you shouldn’t need any special instructions to test your connection, and all users of this package are using the same code path as everyone else. 

If you can still reproduce the issue outside of the proxy, I’d be happy to dig further.
