### ISSUE TITLE
Slack message formatting

### ISSUE THREAD

**Issue by sazarkin** [slack-go/slack#261]
Slack has some rules for message content (like escape &<>)
https://api.slack.com/docs/message-formatting

Do you think I have to manage it myself? Or Slack lib can do this?

I found related code here
https://github.com/nlopes/slack/blob/2643d9b771787c5ce7841ca1f5bb45022ae5eee1/chat.go#L192

But it does not cover all cases.

**Comment by dvdplm** [comment]
There are no plans for a comprehensive "Slack message format API" and other than escaping chars I think we should avoid bloating the code base. Perhaps it could be a useful external package?

**Comment by tappoz** [comment]
I see there are no plans, however until a few months ago `inline single backticks` were working as expected when using this library.

I've tried to dig a bit in the code but I could not isolate the problem / commit ID, it may be Slack themselves changed something on their side - since the same time icons are different, but I am not sure.

At the moment these two calls:

```
client.PostMessage("#my-channel", "message with escaped \\`backticks\\`", slack.PostMessageParameters{})
client.PostMessage("#my-channel", "message with `backticks`", slack.PostMessageParameters{})
```

give back unformatted text.

(single escape backslashes make the compilation fail)

**Comment by james-lawrence** [comment]
we use `` just fine. its something on your end most likely.
