### ISSUE TITLE
Update websocket example for rtm/gorilla websocket dialer.

### ISSUE THREAD

**Issue by andmarios** [slack-go/slack#289]
Hello. Thanks for this very useful library!

An issue I experienced today, is that I had based my code on the websocket example found here:
https://github.com/nlopes/slack/blob/master/examples/websocket/websocket.go#L17

With commit b5448397ba5f9e754fa5a27c6cf28480b462bf29 (found via git bisect) my code stopped working and I had to change:

    rtm := api.NewRTM()

To:

     rtm := api.NewRTM(slack.RTMOptionUseStart(true))

Maybe it should be added to the example? Or this isn't the intended behavior?

**Comment by dvdplm** [comment]
Could this be caused by Slack having deprecated the `connect` call in favour of `start`?

**Comment by james-lawrence** [comment]
could be, i'd like to suggest we change the default to `start` when we break api compat.

@andmarios not sure if its worth changing anything. really the NewRTM should work by default just happens to be in an odd state due to the method having been deprecated by slack, and trying to maintain behaviour.
