### ISSUE TITLE
Obtain channel ID

### ISSUE THREAD

**Issue by leolara** [slack-go/slack#51]
To send a message using the rtm protocol, I need the channel ID, it seems it does not work just using "#channelname".

Then, the problem is how to obtain that ID, as GetChannelInfo does not return it. I think it is returned bu the API, so it should be easy to return from `GetChannelInfo`

**Comment by leocassarani** [comment]
@leolara If you've already established an RTM connection, I would suggest iterating over the `Channels` slice of the `Info` struct to find what you're looking for: https://godoc.org/github.com/nlopes/slack#Info

``` go
func FindChannelByName(rtm *slack.RTM, name string) *slack.Channel {
    for _, ch := range rtm.GetInfo().Channels {
        if ch.Name == name {
            return &ch
        }
    }
    return nil
}
```

The only gotcha there is that if a channel is renamed, the `Info` struct won't get updated. If you need to support that use case, you could keep your own copy of the `Channels` slice and update it manually every time you receive a [ChannelRenameEvent](https://godoc.org/github.com/nlopes/slack#ChannelRenameEvent) over the RTM connection.

Hope this helps!

**Comment by leolara** [comment]
@leocassarani yes, that is what I thought!! But, how do I get the channel ID from the `Channel` struct?

**Comment by leocassarani** [comment]
@leolara `Channel` embeds `groupConversation`, which embeds `conversation`, so you're looking for `channel.ID`: https://github.com/nlopes/slack/blob/4a9ff5f6ed8bb0df51620f49ee90fc0858a2913e/conversation.go#L5

However, I think your confusion is understandable here. Because those embedded structs are private, they don't show up in GoDoc. I myself have struggled with that at one point or another.

@nlopes any thoughts on making those private structs public, or finding some other way to make the fields show up in GoDoc?

**Comment by leolara** [comment]
@leocassarani 

I do not think it is possible to do that, which is a bad thing for godoc.

Why groupConversation and conversation should be private? Perhaps the solution is to make them public.
