### ISSUE TITLE
Failure trying to read block for Zoom call message

### ISSUE THREAD

**Issue by gregmarr** [slack-go/slack#579]
Error "unsupported block type" received trying to parse this message in conversations.history.

        {
            "type": "message",
            "subtype": "bot_message",
            "text": "smith has started a meeting",
            "ts": "1566248229.004500",
            "bot_id": "ABCDEFGHI",
            "blocks": [
                {
                    "type": "call",
                    "call_id": "ABCDEFGHI",
                    "block_id": "jHZ6",
                    "api_decoration_available": false,
                    "call": {
                        "v1": {
                            "id": "ABCDEFGHI",
                            "app_id": "ABCDEFGHI",
                            "app_icon_urls": {
                                "image_32": "some-url.png",
                                "image_36": "some-url.png",
                                "image_48": "some-url.png",
                                "image_64": "some-url.png",
                                "image_72": "some-url.png",
                                "image_96": "some-url.png",
                                "image_128": "some-url.png",
                                "image_192": "some-url.png",
                                "image_512": "some-url.png",
                                "image_1024": "some-url.png",
                                "image_original": "some-url.png"
                            },
                            "date_start": 1566248229,
                            "active_participants": [],
                            "all_participants": [
                                {
                                    "slack_id": "ABCDEFGHI"
                                },
                                {
                                    "external_id": "12345678",
                                    "avatar_url": "",
                                    "display_name": "John Smith"
                                }
                            ],
                            "display_id": "123-456-789",
                            "join_url": "https:\/\/blah.zoom.us\/j\/123456789",
                            "name": "Zoom meeting started by smith",
                            "created_by": "ABCDEFGHI",
                            "date_end": 1566249369,
                            "channels": [
                                "ABCDEFGHI"
                            ],
                            "is_dm_call": false,
                            "was_rejected": false,
                            "was_missed": false,
                            "was_accepted": false,
                            "has_ended": true
                        }
                    }
                }
            ]
        },

**Comment by gregmarr** [comment]
Looks like even more block types are coming:
https://api.slack.com/changelog/2019-09-what-they-see-is-what-you-get-and-more-and-less

**Comment by asf-stripe** [comment]
This is now turning into a bigger problem: people's slack clients are reloading and sending these new types of blocks as a matter of course. Our bots are currently unable to process these messages, because unmarshalling the messages fails.

**Comment by acaloiaro** [comment]
@asf-stripe I've also noticed a recent influx of application crashes induced by this issue. I'm taking a look at it today. 

Update: the recent influx of errors is due to the new `rich_text` message block type due to the general availability of: https://api.slack.com/changelog/2019-09-what-they-see-is-what-you-get-and-more-and-less

Update 2: I believe Slack's API change might warrant a backwards-incompatible API change for this library. Notably, the following statement from the above URL has implications for the semantics of `BlockElements::UnmarshalJSON` error response. 

> Expect to encounter other (even undocumented) elements.

Currently, a non-nil `error` response from `UnmarshalJSON` _can mean_ that a previously-unencountered block element type has been encountered. These semantics are incompatible with Slack's delcaration that they reserve the right to introduce new block element types at any time. 

Because this change from Slack unambiguously breaks all existing applications based on this library, my recommendation is that the semantics around `UnmarshalJSON`'s `error` response be relaxed. It should not return an error upon encountering an unknown block element type, as it is not a true error-state; it should be the expectation of this library that it will encounter unknown block element types. 

`Blocks::UnmarshalJSON`'s semantics should be similar. 

Because both of these are exported functions, I think any changes to their error semantics should be announced. 

I have a stopgap solution implemented on my fork; I'm happy to PR it if others agree with changing the semantics of `UnmarshalJSON`'s `error` response. 

Update 3: This is the change I'm proposing, for reference https://github.com/acaloiaro/slack/pull/1/files

**Comment by acaloiaro** [comment]
Hi @james-lawrence, since the effect of this issue has recently become significantly more widespread, I was hoping to get your thoughts on my proposal above. Cheers.

**Comment by asf-stripe** [comment]
Thanks for the patch, @acaloiaro - I just applied that to the system that was previously failing. It seems to do the right thing and restores functionality. I'd be excited to see it land in master (but with tests, hopefully?!) (:

**Comment by acaloiaro** [comment]
@asf-stripe glad it helped in the mean time! I deliberately left out tests because I wanted to get the community's opinion on my proposed solution first. I'm not a regular contributor to this project, and don't have a good sense of how my change may impact other users of this library. 

I'm also using the patch successfully on a fork of [slack-term](https://github.com/erroneousboat/slack-term), which was previously crashing in every channel I visited.

**Comment by tsein-stripe** [comment]
@acaloiaro Thanks for the patch! I've been contributing to the open PR which supports the Views API https://github.com/nlopes/slack/pull/632 and I have your changes included in a PR that I opened against the author's fork: https://github.com/kanata2/slack/pull/1

Let me know if you want to coordinate on getting this merged in upstream. I just included your patch in my PR because I was running into the same problems described in this issue while testing out my view interactions contributions.

**Comment by acaloiaro** [comment]
FYI @tsein-stripe I've attached my PR to this issue. It's not clear that anyone is actively maintaining this project at the moment, however. I'll see if I can get in contact with @nlopes. I'd be happy to help maintain.

**Comment by acaloiaro** [comment]
FYI @gregmarr my PR was incorporated into https://github.com/slack-go/slack/pull/669 and merged. This issue can be closed.

**Comment by ollieparsley** [comment]
Awesome!
