### ISSUE TITLE
How do I get attention for a Pull Request?

### ISSUE THREAD

**Issue by malkhamis** [slack-go/slack#642]
Hello,
the [PR](https://github.com/nlopes/slack/pull/638) has been there for 10 days, but it doesn't seem like it is getting any attention 🤔

**Comment by bitsofinfo** [comment]
dead project?

**Comment by parsley42** [comment]
I'm working with @ollieparsley to create a new fork of this at github.com/lnxjedi/go-slack. @nlopes - Ollie and I would be adding additional committers from the pool of contributors; would you be amenable to transferring the repo? Individual people projects don't scale well to many developers, so it will be nice to have slack under a github org.

**Comment by nlopes** [comment]
Hello 👋 

Thanks for tagging me here. As you may have noticed, I don't maintain this myself anymore. I'm more than fine to move this if that's appropriate but I'm not sure having it under a org or individual makes that much of a difference in terms of scalability (the same can be true as long as someone is involving maintainers).

I'll add @parsley42 and @ollieparsley to the maintainers for now so that you can move this in the direction needed. In any case, not opposed to a fork - that's part of OSS after all.

**Comment by parsley42** [comment]
Hi @nlopes - good to hear from you. Actually, the reason I asked for a transfer was so that, in the future, I could add additional committers. I don't feel like I can commit to reviewing and approving PRs indefinitely, but I think I there are enough contributors that I can establish a group with commit access, and grant others the ability to add more committers - that's what I mean by scalability of an org-based repo vs. an individual repo, where only the original owner can add committers.

> In any case, not opposed to a fork - that's part of OSS after all.

That's probably the only real long-term solution for me to be able to add committers. Thanks.

**Comment by parsley42** [comment]
@nlopes - another possibility would be for you to create your own org, and a slack maintainers team, then add e.g. myself and Ollie as "team maintainers". Whatever works for scaling the committers...

**Comment by nlopes** [comment]
That's a good shout. I'm going to try to go for slack-go to make the org really obvious.

**Comment by parsley42** [comment]
Hi @malkhamis - Norberto has created a new [slack-go/slack](https://github.com/slack-go/slack) fork, and this PR (along with #650 and #632) have already been merged there. See the tail-end of #632, and let me know if you're interested in being a committer, or would like to recommend another committer. Thanks.

**Comment by 178inaba** [comment]
@nlopes @parsley42 Hello.
If you copy this repository and create a new one, you will lose the history of Issue and Pull Request.
What about using this transfer method instead of creating a new repository?
If so, history will be inherited.

**Transferring a repository owned by your organization**
https://help.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-organization

**Comment by 178inaba** [comment]
Of course, Star and Fork will also be carried over.
It is important for Contributor that Fork takes over.

To keep the current import path, it is a good idea to create a Fork repository of the transferred repository at github.com/nlopes/slack.
The following is an example of gorp.
https://github.com/coopernurse/gorp

**Comment by parsley42** [comment]
Yup, @nlopes could:
* Rename `slack-go/slack` to `slack-go/slack-new`
* Transfer the original to the new org
* Fork from the `slack-go/slack` back to `nlopes/slack` to preserve the import path, potentially with local commits indicating the new version location

... then I could do the `git` dance to merge updates from `slack-go/slack-new` to the transferred `slack-go/slack`. He may have reasons for wanting to keep the original code base separate, so we'll see what he thinks.

**Comment by parsley42** [comment]
@nlopes Just to be clear, I'm not _asking_ you to go this route; just offering to twiddle the git bits if needed. As far as I'm concerned, we're in good shape to go forward now (thanks again), and there's really nothing more I'd ask of you.

**Comment by nlopes** [comment]
I think this would be fine.
Let me go ahead and do the above.

**Comment by nlopes** [comment]
All done. Will also put a README message at `nlopes/slack` to make sure people are aware.

**Comment by nlopes** [comment]
Done as well. Let me know if you need anything else and many thanks for keeping this community alive!

**Comment by 178inaba** [comment]
@nlopes Thanks!
