### ISSUE TITLE
Example for response url

### ISSUE THREAD

**Issue by wiardvanrij** [slack-go/slack#681]
Relates to this feature: #581 

I was wondering if it would be possible that someone could give me an example of how to actually implement this. 

Currently, I'm able to send an interactive block and receive the user's response via `InteractionCallback` 
Yet I'm pretty clueless on how to "update" the block with a response. 

Thanks in advance.

**Comment by sspaink** [comment]
After you unmarshal the InteractionCallback you can post a message to slack using the information in the payload. The [slack api documention](https://api.slack.com/interactivity/handling#message_responses) has more detail, but hopefully the example below helps clarify it as well. With the [MsgOptions](https://godoc.org/github.com/slack-go/slack#MsgOption) you can adjust how your response is received. For example, instead of replacing the original you can use `slack.MsgOptionBroadcast()` to post your response publicly in the channel.

``` 
var payload slack.InteractionCallback
incomingPayload := []byte(r.FormValue("payload"))
_ := json.Unmarshal(incomingPayload, &payload)

_, _, _= api.PostMessage(payload.Channel.ID,
slack.MsgOptionReplaceOriginal(payload.ResponseURL),
slack.MsgOptionText("Hello I am an example to update block with response!", false))
```

Just be sure to respond with an [acknowledgment response](https://api.slack.com/interactivity/handling#acknowledgment_response) within 3 seconds!

**Comment by wiardvanrij** [comment]
Thank you @BattleBas . I haven't got the time to test it, but it makes sense ;)
