### ISSUE TITLE
Feature request: support new Socket Mode feature

### ISSUE THREAD

**Issue by eliot-stripe** [slack-go/slack#883]
https://api.slack.com/apis/connections/socket

**Comment by mumoshu** [comment]
I've submitted a WIP implementation of this at #885 for early reviews.

The biggest blocker for me is that it results in import cycle due to that the code depends on the `slack-go/slack/slackevents` package, where the `slackevents` package already depend on the root package.

Should I move the new feature under `slack-go/slack/socketmode` and force the user to call some factory function under that to initialize a Socket Mode client? Is it acceptable? 🤔

**Comment by kanata2** [comment]
Thanks for your great work!
I'll check later 🙏

**Comment by kanata2** [comment]
@mumoshu 
Sorry for the delay.

> Should I move the new feature under slack-go/slack/socketmode and force the user to call some factory function under that to initialize a Socket Mode client? Is it acceptable? 🤔

I think it's good 😄
