### ISSUE TITLE
Attachment ts field is sometimes a string

### ISSUE THREAD

**Issue by pendowski** [slack-go/slack#90]
I tried dumping messages from direct chats today and with one particular message I got an error:

`json: cannot unmarshal string into Go value of type int64`

After investigation I found that one message has the `ts` field for attachment as a string. I tired replacing the data type for attachment from `int64` to `string` but it started crashing on another user, which means that this field can be both int64 and string.

I'm not fluent in Go to figure out a solution, so here's json of a response that crashes the script (changed names etc. for privacy):

``` json
{
  "ok": true,
  "latest": "1461156109.000043",
  "messages": [
    {
      "type": "message",
      "user": "U025QS77U",
      "text": "<https://something.slack.com/archives/lunch/p1461060720000152>",
      "attachments": [
        {
          "color": "4D394B",
          "from_url": "https://something.slack.com/archives/lunch/p1461060720000152",
          "fallback": "[April 19th, 2016 3:12 AM] someone: &gt; 12 1234 1234 1234 1234 1234 1234",
          "author_subname": "someone",
          "ts": "1461060720.000152",
          "text": "&gt; 12  1234 1234 1234 1234 1234 1234",
          "author_name": "Some User",
          "author_link": "https://something.slack.com/team/someone",
          "author_icon": "https://avatars.slack-edge.com/2015-04-17/12312312312231.jpg",
          "mrkdwn_in": [
            "text"
          ],
          "id": 1
        }
      ],
      "ts": "1461156085.000041"
    }
  ],
  "has_more": true
}
```

**Comment by finack** [comment]
Funny I just ran into this as well. It showed up when I `@ mentioned` the bot in a channel it was not subscribed to, and then instructed slack to send them a message to the mention. The response has `"ts":"1469909830.000018"` in the attachment section.

I changed [the json serializer](https://github.com/nlopes/slack/blob/8379b12e6252483c0a58936698f9536f9f9b61ed/attachments.go#L75) to a `string` and this fixed the issue. Tests pass as well. But not sure what this breaks in reality.

It looks like the [slack docs](https://api.slack.com/docs/message-attachments) do call for an integer but now they are returning a string (as well?).

To replicate follow the NewRTM example, connect to slack, `@ mention` the bot, then `have slackbot send them a link to your message`.

The other thing of interest that I have not figured out is after this happens restarting the bot causes `ConnectingEventErrors` and then you get throttled. It goes away but not sure if it was because of time passing or me messing with `/inviting` and `/kicking` the bot.

**Comment by pendowski** [comment]
I changed to to string as well but it crashed in some other place, not sure if in different person's DM or @yourownnick. Will have to check it tomorrow but I think that changing the type doesn't solve the underlying issue. Is there a way to decode to int even if it's string (or from int to string)? Some custom dynamic mapping in go?

**Comment by mlabouardy** [comment]
use interface{} as data type
see https://github.com/nlopes/slack/issues/115
